docs/Events.md, lib/client.js
appears when you try to chat but you're timed out :o
=> client: added 'msg_timedout' notice

lib/client.js
This change adds some of the notice events that twitch sends in the case of /mod and /unmod commands
=> Add mod events

lib/client.js, test/whisper.js, website/docs/Events.md
Change the whisper username (string) callback argument to a user object with all of the sent tags.
=> Send all whisper tag data

website/docs/Commands.md, website/docs/Database.md, website/docs/Events.md, website/docs/Functions.md
Might look better with a different formatting, so this doesn't have to be _the_ commit to merge. Just a suggestion.
=> docs: duplicate short description to jump lists

lib/client.js
=> client: comment correction

package.json
I'd like to contribute a bit more but not a lot of the module is covered by unit tests, so I feel like I am walking on eggshells. :smile:
=> package: Add code coverage.

gulpfile.js
Remember to return the stream so that gulp can calculate the time taken. :smile:
=> gulp: Correctly report bundling time.

test/websockets.js
What do you think? The error handling tests could be better, consider those placeholders for now. We might want to expose the retry delay so that we can avoid waiting for a long time in the tests. :smile:
=> client: websockets tests.

lib/client.js, lib/commands.js, test/commands.js
Ref: https://github.com/Schmoopiie/tmi.js/issues/108#issuecomment-205521930
Still WIP right now.
I also managed to fix a bug where `_promiseUnhost` was not being called when there was a `no_permission` error.
=> Add some command tests.

test/invalid.js
Similar to https://github.com/Schmoopiie/tmi.js/pull/113 - this patch handles the tests for any invalid server responses.
=> Add tests for handling invalid server responses.

lib/client.js
Closes https://github.com/Schmoopiie/tmi.js/issues/124
=> client: add "bad_host_error" notice

lib/client.js
Fixed issue #152 that appeared between v1.0.0 and v1.0.1.
=> client: fixed hosted subscriptions appearing

lib/api.js, lib/parser.js, lib/utils.js
Split the commits and changed to block level declaration.
=> Fixes #173 : Allow chrome extensions to use XMLHttpRequest instead of jsonp/request api

lib/client.js
Added 5th parameter to the resub event as you are able to resub with Twitch Prime as well. Checking the system message for `Twitch\\sPrime`
=> client: added twitch prime method to resub event

lib/client.js, test/commands.js
=> client: Handle untimeout_success, Fixes #247

.travis.yml, package-lock.json, package.json
=> Updated ws dependecy

package-lock.json, package.json
Finally fix vulnerabilities and fix why the tests wouldn't finish.
=> Fix dependencies and test

lib/client.js, lib/commands.js
See : https://dev.twitch.tv/docs/irc/commands/#clearmsg-twitch-commands
I've not added events as I'm unsure on how to do it.
Here is a [screen capture](https://cdn.discordapp.com/attachments/177149908401258504/511173253650317332/unknown.png) of the event in debug mode.
First one is the message received after executing the command,
The second one is the message received by others
=> Add support for /delete msgid

lib/api.js
merge overwrite method, url & json custom options
in example https://dev.twitch.tv/docs/v5/reference/channels#update-channel need a "PUT" request.
thanks @dragongun100
=> * fixed merge problem

lib/client.js
Not sure how to update the docs though
Produces the following:
=> client: support followers only notice

lib/client.js
Changes:
- Removed unnecessary if statement
- Added the below subscription events:
subgift, anonsubgift, submystery gift, anonsubmysterygift, giftpaidupgrade, anongiftpaidupgrade
- Added raid event
- Added messageremoved event
=> Added a lot of subscription events

lib/client.js, lib/utils.js
This adds the possibility to pass a function to the `identity.password` option. It may return a string or a Promise resolving to a string, which will then be used as the connection password.
=> client: add dynamic password (pass a function instead of a string)

package.json
I'm not the only contributor and these are listed in the readme file.
=> remove contributor

lib/client.js
Checks for bits when performed in action messages
=> Bits in action messages

lib/client.js
=> PASS SCHMOOPIIE is here to stay

README.md
Add shell prompt characters in readme markdown for consistency
=> Consistent shell prompts in readme

README.md, lib/client.js
Hey 👋 
This tiny PR add support for a new option, `messagesLogLevel`, with default `info` value (no breaking change).
It allows everyone to change the log level of the sent and received messages.
Fixes #205, #404
=> Add messagesLogLevel option

package.json
Updated node version listed within package.json.
This should also reflect on the badge within readme.
=> package: update node version

lib/client.js
Hi, 
Very small change that's increadibly easy for you guys to do, just finally saw a chance to contribute to a great project. Cheers!
=> Client: Added 'Announcement' event
