lib/client.js
This notice occurs when the user needs an e-mail address before he can submit chat messages.
>@msg-id=msg_verified_email :tmi.twitch.tv NOTICE #channel :This room requires a verified email address to chat. Please verify your email at http://www.twitch.tv/settings
=> Add notice "msg_verified_email" to NOTICE parser

docs/Configuration.md, lib/client.js, test/logger.js
Allow a custom logger to be provided when creating a client.
A logger should be on the options object through a “logger” property.
A custom logger must have the methods “info”, “warn”, and “error”.
=> client: allow a custom logger

lib/client.js
In environments like Electron, you have access to both module.exports and window.
Without this change tmi.js would not be accessible through `var tmi = require("tmi.js")`
=> Add to module.exports if it exists

lib/client.js
The CLR Browser is based off Chromium 37 which lacks support for certain functions.
=> client: added support for older browsers

lib/commands.js
tmi.js running in Safari throws the following error:
```
[Error] SyntaxError: Cannot declare a parameter named 's' as it shadows the name of a strict mode function.
(anonymous function) (tmi.js:1)
```
This change renames the `color` variable to `newColor` to avoid that conflict.
=> commands: rename color to newColor to avoid name conflict that breaks on safari

test/noop.js
Should we need to refactor those switch statements in `handleMessage`, it would be nice to have tests for those cases that we shouldn't do anything with. :smile:
=> Add tests for messages that should be no-ops.

lib/logger.js, lib/utils.js, package.json, test/logger.js
* Extracted out the format date function into utils, decoupling it from the log.
* Made the format date function take a `Date` parameter for easier testing.
* Use 24 hour time. If we want 12 hour time we should write `08:30pm` rather than `20:30pm` which is confusing/unnecessary. Personally I think that 12 hour time could be optional, would much rather see 24 by default, it's shorter.
=> logger: Use 24 hour time, add tests.

lib/client.js, lib/utils.js
We don't need to call a function with the server details, seems a little wasteful. I changed the method to return strings instead, it's simpler and it allows us to consolidate the server connection code into one block.
=> Refactor server joining code.

lib/commands.js, test/commands.js
Currently, `.say('#channel', '.me derp')` does not fire an `action` nor a `chat` event. This PR fixes it by not 
checking the prefixes twice.
=> client: fix ".me" command (replaces #110)

lib/client.js, test/events.js
This new, last argument for the join and part events is `true` when the username is the same as the client.
You no longer have to write unnecessary code to check this:
**Old**
```javascript
client.on('join', (channel, username) => {
if(username === client.username()) {
console.log('Joined', channel);
}
});
```
**New**
```javascript
client.on('join', (channel, username, fromSelf) => {
if(fromSelf) {
console.log('Joined', channel);
}
});
```
Another option would be to emit "join-self" and "part-self" respectively, but I don't think adding more events is necessary.
=> client: emit boolean with join/part events.

lib/api.js, lib/client.js, lib/commands.js, lib/utils.js, sri.js, test/authentication.js, test/client.js, test/commands.js, test/events.js, test/invalid.js, test/logger.js, test/noop.js, test/websockets.js
This pull request will alter the "whisper" and "message" events to include as much information as possible. The `channel` argument will no longer be `null` and will contain the channel-formatted name of the other user in the conversation. The "whisper" event callback arguments now match the other chat-type events including the "self" argument whether or not the message was sent since it already resolves either way.
This pull request also changes some string concatenations to "template strings where sane" and to match some other string concatenations elsewhere.
This also changes the tests' library declarations of `irc` to `tmi` instead.
```javascript
const tmi = require('tmi.js');
let client = new tmi.client({
identity:{
username: 'alcabot',
password: '...'
}
});
client.on('whisper', …
```
=> Emit self whispers

lib/client.js
Can either be a single channel or a comma-delimited list of channels.
=> client: allow passing a string for the channels option.

lib/client.js
When handling automated actions for your Users the login name is (way more) useful for that than the username, especially if that one is localized.
Seeing as the Info is there, but just not emitted i think it would be useful to output that, at least for resubs.
=> Improvement: Output the login-name alongside of the username for resubscription notices

lib/client.js
A Client ID is required for the emotesets API request - suggest a 'General' category that allows users to set their `clientId` to prevent the request from failing.
=> client: set custom Client-ID for emotesets API call

lib/client.js
Originally I was just passing the boolean as a 3rd parameter but figured it would be cleaner for future compatibility if we passed an object.  That way if Twitch adds any more things like this, we can just add the  value to the object instead of A) passing it as a 4th param or B) instituting a breaking change by changing the boolean to an object.
Will update docs if merged.
=> client: added 3rd parameter to subscription callback thats contains an amazon prime sub boolean

lib/client.js
Added a bool parameter to the hosted event showing if the host was an auto-host. The message I based my changes off of was: `DBKynd is now auto hosting you.` 
I'm making an assumption here that the message for auto host with viewers would be `DBKynd is now auto hosting you for 10 viewers.` as I don't have an easy method for testing without setting up alt accounts to 'view' and then host.
=> client: added auto-host bool parameter to hosted event

lib/client.js, test/events.js
After the discussion in #191, I've decided that the first option would be the most sane one. Just did it right here, added the userstate as fifth parameter to the resub events, to allow users to get the details of the message (emotes, display name, ...) without breaking backwards compatibility.
The tests didn't run at all on my machine, hope they are okay.
=> client: add userstate to resub events - fixes #191

index.js
I'd like to have the client constructor with a capital `c` so I can use this in a project that requires constructors to begin with a capital letter. (StandardJS)
I left the lower-case constructor in so it won't break anybody's projects.
Thanks.
=> Add capitalised alias to client constructor.

lib/client.js, test/events.js
Addressing: https://github.com/tmijs/tmi.js/issues/222
According to
https://discuss.dev.twitch.tv/t/subscriptions-beta-changes/10023
New subscriptions are now handled as a USERNOTICE similarly to resubs,
and the method object can now include a plan and planName.
Additionally, users can now provide a message upon subscribing, so a msg
and userstate is now provided. This is a lot of parameters, but it
should be backwards compatible with any code that was designed for the
old twitchnotify version.
=> client: subscription handling changed from twitchnotify to usernotice

lib/client.js
Add some msgids on notice event listeners (referenced : https://dev.twitch.tv/docs/irc/msg-id/)
These msgids are not processed on tmi.js 1.2.1, and make warn logs.
Handling of msgid, 'msg_rejected_mandatory' is on [here ](https://github.com/tmijs/tmi.js/pull/273) .(already pulled) .
=> Add some msg_ids on notice event listeners

lib/client.js
The constructor of the EventEmtiter (events.js) overrides the _maxListeners variable if its 0 or undefined or smth else. Due to calling the EventEmitter constructor after setMaxListerns(0) makes line 13 completely useless.
Disables the should allready disabled "warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit." message.
=> client: fix MaxListeners before override by EventEmitter

lib/client.js, test/client.js
@Meerkov proposed this change in #395 but that PR went stale
I changed the commit message as requested
Closes #395 
Fixes #394
=> client: secure now defaults to true (fixes #394)

lib/client.js, lib/commands.js, test/commands.js
`client.whisper()` now rejects, for now only when one of the following notices arrive within the `_getPromiseDelay()` time-span: 
* `no_permission`
* `whisper_invalid_login`
* `whisper_invalid_self`
* `whisper_limit_per_min`
* `whisper_limit_per_sec`
* `whisper_restricted`
* `whisper_restricted_recipient`
This closes #388 
This is a breaking change
=> client.whisper() now rejects

lib/client.js
The USERSTATE message contains the channel that it's
being sent for but this was not being used. Instead it used
the `this.lastJoined` variable. However, this internal variable
is only updated after the tracking for moderators is completed.
This results in moderator status being assigned to the wrong 
channel and will result in `client.isMod` returning `false` when 
called in an `onJoin` handler (or thereafter).
=> Fix moderator tracking for USERSTATE messages

lib/client.js
Without this header, Kraken defaults to V3 which is now deprecated:
`{"error":"Gone","status":410,"message":"v3 is a lie but v5 is still alive. See https://dev.twitch.tv/docs"}`
=> Add Accept header to emoticon_images request

lib/client.js, test/events.js, test/noop.js
Alternative servers send multiple MOTD lines, which is totally fine by the IRC spec, but makes tmi.js emit the connected event (and try to join channels) multiple times.
=> Assume connection success on MOTD end, not MOTD line

lib/utils.js
Fixes #443
This ensures that the type of `msg` is `string` before attempting to parse it in `unescapeIRC`.
Otherwise it leads to an error like "TypeError: msg.includes is not a function at Object.unescapeIRC " when `msg-param-sub-plan` is coerced to a type other than string by a call to `_.get` further up the stack, thus crashing the client.
=> Ensure type of msg is string in unescapeIRC
